services:
  springboot-app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml

  alert-manager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    command: --config.file=/alertmanager/alertmanager.yml --log.level=debug

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      -  ./grafana/datasource-config.yml:/etc/grafana/provisioning/datasources/datasource-config.yml